---
title: "Five Minute Baby Steps"
author: "Adam O'Dell"
date: "Tuesday, July 14, 2015"
output: html_document
---

First things, first: let's load the data into a dataframe (df).


```r
df <- read.csv("activity.csv")
```

Next, we'll check to make sure the dimensions are what we expect (17568 x 3):


```r
dim(df)
```

```
## [1] 17568     3
```

And double-check the column/variable heading:


```r
names(df)
```

```
## [1] "steps"    "date"     "interval"
```

And glance at the "head" of the dataset:


```r
head(df)
```

```
##   steps       date interval
## 1    NA 2012-10-01        0
## 2    NA 2012-10-01        5
## 3    NA 2012-10-01       10
## 4    NA 2012-10-01       15
## 5    NA 2012-10-01       20
## 6    NA 2012-10-01       25
```

All looks well. Now, let's do some analysis.

First, we want to calculate the Total (i.e. sum) number of steps taken each day (TPD = TotalperDay).


```r
TPD <- aggregate(. ~ date, data =df, sum)
TPD
```

```
##          date steps interval
## 1  2012-10-02   126   339120
## 2  2012-10-03 11352   339120
## 3  2012-10-04 12116   339120
## 4  2012-10-05 13294   339120
## 5  2012-10-06 15420   339120
## 6  2012-10-07 11015   339120
## 7  2012-10-09 12811   339120
## 8  2012-10-10  9900   339120
## 9  2012-10-11 10304   339120
## 10 2012-10-12 17382   339120
## 11 2012-10-13 12426   339120
## 12 2012-10-14 15098   339120
## 13 2012-10-15 10139   339120
## 14 2012-10-16 15084   339120
## 15 2012-10-17 13452   339120
## 16 2012-10-18 10056   339120
## 17 2012-10-19 11829   339120
## 18 2012-10-20 10395   339120
## 19 2012-10-21  8821   339120
## 20 2012-10-22 13460   339120
## 21 2012-10-23  8918   339120
## 22 2012-10-24  8355   339120
## 23 2012-10-25  2492   339120
## 24 2012-10-26  6778   339120
## 25 2012-10-27 10119   339120
## 26 2012-10-28 11458   339120
## 27 2012-10-29  5018   339120
## 28 2012-10-30  9819   339120
## 29 2012-10-31 15414   339120
## 30 2012-11-02 10600   339120
## 31 2012-11-03 10571   339120
## 32 2012-11-05 10439   339120
## 33 2012-11-06  8334   339120
## 34 2012-11-07 12883   339120
## 35 2012-11-08  3219   339120
## 36 2012-11-11 12608   339120
## 37 2012-11-12 10765   339120
## 38 2012-11-13  7336   339120
## 39 2012-11-15    41   339120
## 40 2012-11-16  5441   339120
## 41 2012-11-17 14339   339120
## 42 2012-11-18 15110   339120
## 43 2012-11-19  8841   339120
## 44 2012-11-20  4472   339120
## 45 2012-11-21 12787   339120
## 46 2012-11-22 20427   339120
## 47 2012-11-23 21194   339120
## 48 2012-11-24 14478   339120
## 49 2012-11-25 11834   339120
## 50 2012-11-26 11162   339120
## 51 2012-11-27 13646   339120
## 52 2012-11-28 10183   339120
## 53 2012-11-29  7047   339120
```

Visual learners, like myself, will prefer to see that data as a histogram:


```r
Steps_Per_Day <- TPD$steps
hist(Steps_Per_Day)
```

![plot of chunk unnamed-chunk-6](figure/unnamed-chunk-6-1.png) 

Next, let's compute two simple summary statistics: mean and median.


```r
steps_mean <- mean(Steps_Per_Day)
steps_median <- median(Steps_Per_Day)

steps_mean
```

```
## [1] 10766.19
```

```r
steps_median
```

```
## [1] 10765
```

Now, let's "drill down" and look more closely at each 5-minute interval.

Just as we look at statistics for each data, let's do the same for each interval (API = AveragePerInterval).


```r
API <- aggregate(.~interval, data=df, mean)

API
```

```
##     interval       steps     date
## 1          0   1.7169811 30.71698
## 2          5   0.3396226 30.71698
## 3         10   0.1320755 30.71698
## 4         15   0.1509434 30.71698
## 5         20   0.0754717 30.71698
## 6         25   2.0943396 30.71698
## 7         30   0.5283019 30.71698
## 8         35   0.8679245 30.71698
## 9         40   0.0000000 30.71698
## 10        45   1.4716981 30.71698
## 11        50   0.3018868 30.71698
## 12        55   0.1320755 30.71698
## 13       100   0.3207547 30.71698
## 14       105   0.6792453 30.71698
## 15       110   0.1509434 30.71698
## 16       115   0.3396226 30.71698
## 17       120   0.0000000 30.71698
## 18       125   1.1132075 30.71698
## 19       130   1.8301887 30.71698
## 20       135   0.1698113 30.71698
## 21       140   0.1698113 30.71698
## 22       145   0.3773585 30.71698
## 23       150   0.2641509 30.71698
## 24       155   0.0000000 30.71698
## 25       200   0.0000000 30.71698
## 26       205   0.0000000 30.71698
## 27       210   1.1320755 30.71698
## 28       215   0.0000000 30.71698
## 29       220   0.0000000 30.71698
## 30       225   0.1320755 30.71698
## 31       230   0.0000000 30.71698
## 32       235   0.2264151 30.71698
## 33       240   0.0000000 30.71698
## 34       245   0.0000000 30.71698
## 35       250   1.5471698 30.71698
## 36       255   0.9433962 30.71698
## 37       300   0.0000000 30.71698
## 38       305   0.0000000 30.71698
## 39       310   0.0000000 30.71698
## 40       315   0.0000000 30.71698
## 41       320   0.2075472 30.71698
## 42       325   0.6226415 30.71698
## 43       330   1.6226415 30.71698
## 44       335   0.5849057 30.71698
## 45       340   0.4905660 30.71698
## 46       345   0.0754717 30.71698
## 47       350   0.0000000 30.71698
## 48       355   0.0000000 30.71698
## 49       400   1.1886792 30.71698
## 50       405   0.9433962 30.71698
## 51       410   2.5660377 30.71698
## 52       415   0.0000000 30.71698
## 53       420   0.3396226 30.71698
## 54       425   0.3584906 30.71698
## 55       430   4.1132075 30.71698
## 56       435   0.6603774 30.71698
## 57       440   3.4905660 30.71698
## 58       445   0.8301887 30.71698
## 59       450   3.1132075 30.71698
## 60       455   1.1132075 30.71698
## 61       500   0.0000000 30.71698
## 62       505   1.5660377 30.71698
## 63       510   3.0000000 30.71698
## 64       515   2.2452830 30.71698
## 65       520   3.3207547 30.71698
## 66       525   2.9622642 30.71698
## 67       530   2.0943396 30.71698
## 68       535   6.0566038 30.71698
## 69       540  16.0188679 30.71698
## 70       545  18.3396226 30.71698
## 71       550  39.4528302 30.71698
## 72       555  44.4905660 30.71698
## 73       600  31.4905660 30.71698
## 74       605  49.2641509 30.71698
## 75       610  53.7735849 30.71698
## 76       615  63.4528302 30.71698
## 77       620  49.9622642 30.71698
## 78       625  47.0754717 30.71698
## 79       630  52.1509434 30.71698
## 80       635  39.3396226 30.71698
## 81       640  44.0188679 30.71698
## 82       645  44.1698113 30.71698
## 83       650  37.3584906 30.71698
## 84       655  49.0377358 30.71698
## 85       700  43.8113208 30.71698
## 86       705  44.3773585 30.71698
## 87       710  50.5094340 30.71698
## 88       715  54.5094340 30.71698
## 89       720  49.9245283 30.71698
## 90       725  50.9811321 30.71698
## 91       730  55.6792453 30.71698
## 92       735  44.3207547 30.71698
## 93       740  52.2641509 30.71698
## 94       745  69.5471698 30.71698
## 95       750  57.8490566 30.71698
## 96       755  56.1509434 30.71698
## 97       800  73.3773585 30.71698
## 98       805  68.2075472 30.71698
## 99       810 129.4339623 30.71698
## 100      815 157.5283019 30.71698
## 101      820 171.1509434 30.71698
## 102      825 155.3962264 30.71698
## 103      830 177.3018868 30.71698
## 104      835 206.1698113 30.71698
## 105      840 195.9245283 30.71698
## 106      845 179.5660377 30.71698
## 107      850 183.3962264 30.71698
## 108      855 167.0188679 30.71698
## 109      900 143.4528302 30.71698
## 110      905 124.0377358 30.71698
## 111      910 109.1132075 30.71698
## 112      915 108.1132075 30.71698
## 113      920 103.7169811 30.71698
## 114      925  95.9622642 30.71698
## 115      930  66.2075472 30.71698
## 116      935  45.2264151 30.71698
## 117      940  24.7924528 30.71698
## 118      945  38.7547170 30.71698
## 119      950  34.9811321 30.71698
## 120      955  21.0566038 30.71698
## 121     1000  40.5660377 30.71698
## 122     1005  26.9811321 30.71698
## 123     1010  42.4150943 30.71698
## 124     1015  52.6603774 30.71698
## 125     1020  38.9245283 30.71698
## 126     1025  50.7924528 30.71698
## 127     1030  44.2830189 30.71698
## 128     1035  37.4150943 30.71698
## 129     1040  34.6981132 30.71698
## 130     1045  28.3396226 30.71698
## 131     1050  25.0943396 30.71698
## 132     1055  31.9433962 30.71698
## 133     1100  31.3584906 30.71698
## 134     1105  29.6792453 30.71698
## 135     1110  21.3207547 30.71698
## 136     1115  25.5471698 30.71698
## 137     1120  28.3773585 30.71698
## 138     1125  26.4716981 30.71698
## 139     1130  33.4339623 30.71698
## 140     1135  49.9811321 30.71698
## 141     1140  42.0377358 30.71698
## 142     1145  44.6037736 30.71698
## 143     1150  46.0377358 30.71698
## 144     1155  59.1886792 30.71698
## 145     1200  63.8679245 30.71698
## 146     1205  87.6981132 30.71698
## 147     1210  94.8490566 30.71698
## 148     1215  92.7735849 30.71698
## 149     1220  63.3962264 30.71698
## 150     1225  50.1698113 30.71698
## 151     1230  54.4716981 30.71698
## 152     1235  32.4150943 30.71698
## 153     1240  26.5283019 30.71698
## 154     1245  37.7358491 30.71698
## 155     1250  45.0566038 30.71698
## 156     1255  67.2830189 30.71698
## 157     1300  42.3396226 30.71698
## 158     1305  39.8867925 30.71698
## 159     1310  43.2641509 30.71698
## 160     1315  40.9811321 30.71698
## 161     1320  46.2452830 30.71698
## 162     1325  56.4339623 30.71698
## 163     1330  42.7547170 30.71698
## 164     1335  25.1320755 30.71698
## 165     1340  39.9622642 30.71698
## 166     1345  53.5471698 30.71698
## 167     1350  47.3207547 30.71698
## 168     1355  60.8113208 30.71698
## 169     1400  55.7547170 30.71698
## 170     1405  51.9622642 30.71698
## 171     1410  43.5849057 30.71698
## 172     1415  48.6981132 30.71698
## 173     1420  35.4716981 30.71698
## 174     1425  37.5471698 30.71698
## 175     1430  41.8490566 30.71698
## 176     1435  27.5094340 30.71698
## 177     1440  17.1132075 30.71698
## 178     1445  26.0754717 30.71698
## 179     1450  43.6226415 30.71698
## 180     1455  43.7735849 30.71698
## 181     1500  30.0188679 30.71698
## 182     1505  36.0754717 30.71698
## 183     1510  35.4905660 30.71698
## 184     1515  38.8490566 30.71698
## 185     1520  45.9622642 30.71698
## 186     1525  47.7547170 30.71698
## 187     1530  48.1320755 30.71698
## 188     1535  65.3207547 30.71698
## 189     1540  82.9056604 30.71698
## 190     1545  98.6603774 30.71698
## 191     1550 102.1132075 30.71698
## 192     1555  83.9622642 30.71698
## 193     1600  62.1320755 30.71698
## 194     1605  64.1320755 30.71698
## 195     1610  74.5471698 30.71698
## 196     1615  63.1698113 30.71698
## 197     1620  56.9056604 30.71698
## 198     1625  59.7735849 30.71698
## 199     1630  43.8679245 30.71698
## 200     1635  38.5660377 30.71698
## 201     1640  44.6603774 30.71698
## 202     1645  45.4528302 30.71698
## 203     1650  46.2075472 30.71698
## 204     1655  43.6792453 30.71698
## 205     1700  46.6226415 30.71698
## 206     1705  56.3018868 30.71698
## 207     1710  50.7169811 30.71698
## 208     1715  61.2264151 30.71698
## 209     1720  72.7169811 30.71698
## 210     1725  78.9433962 30.71698
## 211     1730  68.9433962 30.71698
## 212     1735  59.6603774 30.71698
## 213     1740  75.0943396 30.71698
## 214     1745  56.5094340 30.71698
## 215     1750  34.7735849 30.71698
## 216     1755  37.4528302 30.71698
## 217     1800  40.6792453 30.71698
## 218     1805  58.0188679 30.71698
## 219     1810  74.6981132 30.71698
## 220     1815  85.3207547 30.71698
## 221     1820  59.2641509 30.71698
## 222     1825  67.7735849 30.71698
## 223     1830  77.6981132 30.71698
## 224     1835  74.2452830 30.71698
## 225     1840  85.3396226 30.71698
## 226     1845  99.4528302 30.71698
## 227     1850  86.5849057 30.71698
## 228     1855  85.6037736 30.71698
## 229     1900  84.8679245 30.71698
## 230     1905  77.8301887 30.71698
## 231     1910  58.0377358 30.71698
## 232     1915  53.3584906 30.71698
## 233     1920  36.3207547 30.71698
## 234     1925  20.7169811 30.71698
## 235     1930  27.3962264 30.71698
## 236     1935  40.0188679 30.71698
## 237     1940  30.2075472 30.71698
## 238     1945  25.5471698 30.71698
## 239     1950  45.6603774 30.71698
## 240     1955  33.5283019 30.71698
## 241     2000  19.6226415 30.71698
## 242     2005  19.0188679 30.71698
## 243     2010  19.3396226 30.71698
## 244     2015  33.3396226 30.71698
## 245     2020  26.8113208 30.71698
## 246     2025  21.1698113 30.71698
## 247     2030  27.3018868 30.71698
## 248     2035  21.3396226 30.71698
## 249     2040  19.5471698 30.71698
## 250     2045  21.3207547 30.71698
## 251     2050  32.3018868 30.71698
## 252     2055  20.1509434 30.71698
## 253     2100  15.9433962 30.71698
## 254     2105  17.2264151 30.71698
## 255     2110  23.4528302 30.71698
## 256     2115  19.2452830 30.71698
## 257     2120  12.4528302 30.71698
## 258     2125   8.0188679 30.71698
## 259     2130  14.6603774 30.71698
## 260     2135  16.3018868 30.71698
## 261     2140   8.6792453 30.71698
## 262     2145   7.7924528 30.71698
## 263     2150   8.1320755 30.71698
## 264     2155   2.6226415 30.71698
## 265     2200   1.4528302 30.71698
## 266     2205   3.6792453 30.71698
## 267     2210   4.8113208 30.71698
## 268     2215   8.5094340 30.71698
## 269     2220   7.0754717 30.71698
## 270     2225   8.6981132 30.71698
## 271     2230   9.7547170 30.71698
## 272     2235   2.2075472 30.71698
## 273     2240   0.3207547 30.71698
## 274     2245   0.1132075 30.71698
## 275     2250   1.6037736 30.71698
## 276     2255   4.6037736 30.71698
## 277     2300   3.3018868 30.71698
## 278     2305   2.8490566 30.71698
## 279     2310   0.0000000 30.71698
## 280     2315   0.8301887 30.71698
## 281     2320   0.9622642 30.71698
## 282     2325   1.5849057 30.71698
## 283     2330   2.6037736 30.71698
## 284     2335   4.6981132 30.71698
## 285     2340   3.3018868 30.71698
## 286     2345   0.6415094 30.71698
## 287     2350   0.2264151 30.71698
## 288     2355   1.0754717 30.71698
```

Again, a VISUAL will help...


```r
plot(API$interval, API$steps, type = "l")
```

![plot of chunk unnamed-chunk-9](figure/unnamed-chunk-9-1.png) 

Visually, it's easy to see the "spike" in steps.

But if someone asked you, "Which specific interval averages the most steps?"

We'd have to calculate that...


```r
MaxInterval <- API[which(API$steps == max(API$steps)),]
MaxInterval
```

```
##     interval    steps     date
## 104      835 206.1698 30.71698
```

OK, so Interval #835 is the winner, with 206.2 steps on average.

Now, let's move on to something altogether different.

There seem to be some missing values (i.e. "NA"s) in our dataset. See...


```r
head(df)
```

```
##   steps       date interval
## 1    NA 2012-10-01        0
## 2    NA 2012-10-01        5
## 3    NA 2012-10-01       10
## 4    NA 2012-10-01       15
## 5    NA 2012-10-01       20
## 6    NA 2012-10-01       25
```

Let's address those missing values.


First, let's figure out how many rows within our dataset contain at least one missing value (i.e. "NA").


```r
TotalNAs <- sum(is.na(df))
TotalNAs
```

```
## [1] 2304
```

Wow, 2304 missing values... that's a lot.

Let's now devise a simple strategy for replacing those missing values. There are many ways to do this.

I'll choose this one: replace any NA value with the value equal to the average value of the interval in question.  


```r
df_new <- df

df_new$steps <- ifelse(is.na(df_new$steps) == TRUE, API$steps[API$interval %in% df_new$interval], df_new$steps)
```

Let's see if that worked...


```r
head(df_new)
```

```
##       steps       date interval
## 1 1.7169811 2012-10-01        0
## 2 0.3396226 2012-10-01        5
## 3 0.1320755 2012-10-01       10
## 4 0.1509434 2012-10-01       15
## 5 0.0754717 2012-10-01       20
## 6 2.0943396 2012-10-01       25
```

```r
tail(df_new)
```

```
##           steps       date interval
## 17563 2.6037736 2012-11-30     2330
## 17564 4.6981132 2012-11-30     2335
## 17565 3.3018868 2012-11-30     2340
## 17566 0.6415094 2012-11-30     2345
## 17567 0.2264151 2012-11-30     2350
## 17568 1.0754717 2012-11-30     2355
```

```r
sum(is.na(df_new))
```

```
## [1] 0
```

Looks good to me!

Now, let's make a histogram of the new dataframe, which is equivalent to the original dataframe, only with all the NAs replaced.


```r
TotalPerDay <- aggregate(. ~ date, data=df_new, sum)

Steps_Per_Day <- TotalPerDay$steps
hist(Steps_Per_Day)
```

![plot of chunk unnamed-chunk-15](figure/unnamed-chunk-15-1.png) 

Visually, that histogram looks just like the original histogram of Total Steps Per Day, which had missing NAs value.

But let's be more precise. Calculating the mean and median of our new dataset, with NAs replaced, will help.


```r
new_mean <- mean(Steps_Per_Day)
new_median <- median(Steps_Per_Day)

new_mean
```

```
## [1] 10766.19
```

```r
new_median
```

```
## [1] 10766.19
```
Compared to the "original" values:


```r
steps_mean
```

```
## [1] 10766.19
```

```r
steps_median
```

```
## [1] 10765
```

The mean has not changed at all. And the median has changed only ever so slightly (basically, it hasn't changed).

Sadly, it seems our replacement of the NAs had no effect... it was a waste of time (except I'm learning R!)

Now, let's explore one last thing.

I wonder if people take more steps on Weekdays versus Weekend Days.

First, we have to create a new variable - one that defines the date variable as either: "Weekday" or "Weekend". That sounds like a "factor" variable with two levels.

We'll start this work on our "NA-replaced" dataset (i.e. df_new)


```r
df_new$date <- as.Date(df_new$date)

weekdays1 <- c('Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday')

df_new$wDay <- factor((weekdays(df_new$date) %in% weekdays1), levels = c(FALSE,TRUE), labels=c('Weekend','Weekday'))
```

Let's make sure our new variable is a "factor" variable:


```r
class(df_new$wDay)
```

```
## [1] "factor"
```

And glance at the head of our new dataset:


```r
head(df_new)
```

```
##       steps       date interval    wDay
## 1 1.7169811 2012-10-01        0 Weekday
## 2 0.3396226 2012-10-01        5 Weekday
## 3 0.1320755 2012-10-01       10 Weekday
## 4 0.1509434 2012-10-01       15 Weekday
## 5 0.0754717 2012-10-01       20 Weekday
## 6 2.0943396 2012-10-01       25 Weekday
```

Good, all looks well!

Next, let's subset this dataset based on our Weekday/Weekend factor variable:


```r
weekend_set <- subset(df_new, wDay == "Weekend")

weekday_set <- subset(df_new, wDay == "Weekday")
```

Now we can compute the Average Steps per Interval, for each subset:


```r
API_weekend <- aggregate(. ~ interval, data = weekend_set, mean)
API_weekend$wDay <- factor("Weekend")

API_weekday <- aggregate(. ~ interval, data = weekday_set, mean)
API_weekday$wDay <- factor("Weekday")
```

Let's recombine those subsets, to make a Panel Plot easier.


```r
new_API <- rbind(API_weekend,API_weekday)
```

And, finally, make a Panel plot... comparing the diference in Average Steps per Interval for Weekdays versus Weekends:


```r
library(lattice)
xyplot(steps ~ interval | wDay,
        data = new_API,
        type = "l",
        xlab = "Interval",
        ylab = "Average Steps",
        layout = c(1,2))
```

![plot of chunk unnamed-chunk-24](figure/unnamed-chunk-24-1.png) 

Interesting!

It seems that on Weekdays, more steps are taken between the 500 and 1000 intervals.

But on Weekends, more steps are taken between the 1000 and 2000 intervals.

Although, overall, the patterns of activity are very similar on both Weekdays and Weekends.

This was a fun investigation of data!

See you next time...
